### ISSUE TITLE
JSON Schema Validator issues a generic RuntimeException when a numeric value is set as string 

### ISSUE THREAD

**Issue by ddobrin** [networknt/json-schema-validator#122]
A developer at a client reported the following issue:

OpenAPI spec sets the following values as integers, using the int32 format:
```
properties:
        externalID:
          description: ...
          type: integer
          format: int32
        type:
          description: ...
          type: integer
          format: int32
```

In the request, the client sends : 
```
            "externalID" : "389" , 
            "type" : 54, 
```

and encounters a failure:
```
    "error" : { 
        "statusCode" : 500, 
        "code" : "ERR10010" , 
        "message" : "RUNTIME_EXCEPTION" , 
        "description" : "Unexpected runtime exception" , 
        "severity" : "ERROR" 
    }
``` 
The client expects a validation error

Please note that: the "error" element is correct, as the error serialization includes this element for my client.

**Comment by stevehu** [comment]
@ddobrin Could you please look into the log file to get the stacktrace? Also, are the properties in header or body?

**Comment by ddobrin** [comment]
@stevehu - the properties are in the body of the request

I will ask the client to provide the stacktrace, as I do not have it yet

**Comment by stevehu** [comment]
If it is the body, then "389" might be the problem. The type is an integer but the value is passed in as a string. unlike the query parameters, we don't do any auto conversion for the body properties.

**Comment by jiachen1120** [comment]
@ddobrin Hey! I have tested this feature but cannot reproduce. I used the specification below and sent a request. Then I got the correct response.
```
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
```
request I sent (post method to create new pet): 
```
{"id":"123","name":"456"}
```
response I got:
```
{"statusCode":400,"code":"ERR11004","message":"VALIDATOR_SCHEMA","description":"Schema Validation Error - $.id: string found, integer expected","severity":"ERROR"}
```

In addition, I also tested the path parameters and also worked fine. Normally, the validator will only return a Status. To get an error you described, you need a method that throws a runtime exception and is caught by the exception handler. It seems that this does not happen during the verification process.

So could you please provide some log information so that I can further analyze it to solve this problem? Thank you
