### ISSUE TITLE
Validate nullable enhancement

### ISSUE THREAD

**Issue by jiachen1120** [networknt/json-schema-validator#126]
There are two concerns related to nullable validation:

**[1]** When verifying the response, if the value corresponding to a field is null and the nullable is not set in specification. The verification will not pass. Even this field is not required. 

For example, assuming that we want get a pet object from the response and validating the response by using the following schema
```
Pet: 
  type: object
  required:
    - name
  properties:
    id:
      type: string
```
And the response we got is `{"name": "dog", "id": null}`, the validation would fail due to the `nullable` default value is false. If we want to pass the validation, the specification should be correct in this way:
```
Pet: 
  type: object
  required:
    - name
  properties:
    id:
      type: string
      nullable: true
```

This may not be very reasonable. When setting required, the user needs to set nullable to true at the same time if they would receive a null field. This may increase the complexity of the specification. So I wonder if we can set the default value of nullable to true?

**[2]** Nullable cannot be recognized when using following specification:
```
  properties:
    id:
      $ref: '#/components/schema/id'
      nullable: true
```
The reason is that when using JsonOverlay.toJson() to get JsonNode, the nullable would be erased if this field need to refer others. One easy way is to suggest user to use following specification
 ```
  properties:
    id:
      oneOf:
      - $ref: '#/components/schema/id'
      - nullable: true
```
Or, we need to modify JsonOverlay

Look forward to your ideas!
