### ISSUE TITLE
Root properties of a model described by a schema are always validated as required

### ISSUE THREAD

**Issue by tucek** [networknt/json-schema-validator#73]
A RequiredValidator initialized with all property names is created for the root level described by a schema. JSON schema allows for optional properties also in the root level of a described model.

sample-schema.yaml
```
%YAML 1.2
---
$schema: http://json-schema.org/draft-04/schema#
additionalProperties: false
description: Example.
properties:
  property1:
    type: string
  property2:
    type: string
required:
 - property1
...
```

sample.yaml
```
%YAML 1.2
---
property1: TEST
...
```

result
```
$.property2: is missing but it is required
```
